[tool.darker]
src = [
    "sandbox",
]
revision = "main"
diff = false
check = false
isort = false
flynt = false
line-length = 88
log_level = "INFO"
color = true

[tool.black]
skip-string-normalization = true
line-length = 88
force_exclude = ".*.pyi"

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
# rules to check (https://beta.ruff.rs/docs/rules)
select = [
    "F",        # pyflakes
    "E", "W",   # pycodestyle
    "C90",      # mccabe
    "ERA",      # eradicate
    "N",        # pep8-naming
    "B",        # flake8-bugbear
    "T20",      # flake8-print
    "RET",      # flake8-return
    "TCH",      # flake8-type-checking
]
ignore = []

# allow autofix for all enabled rules (when `--fix`) is provided
# example:
# fixable = [
#     "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN",
#     "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN",
#     "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET",
#     "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
# ]

# disable autofix for some possibly-unsafe rules
unfixable = ["B", "SIM", "TRY", "RUF"]

# exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 88
# allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# assume Python 3.10
target-version = "py310"

[tool.ruff.mccabe]
# default to a complexity level of 10
max-complexity = 10
